/** Settings styling built exclusively on the Harness Web semantic theme tokens. */

const ID = 'deepseek-tag-settings-styles'

const CSS = `
.dst-section{box-sizing:border-box;display:flex;flex-direction:column;gap:14px;max-width:760px;padding:2px 0 28px;color:var(--dsw-alias-label-primary)}
.dst-section h2,.dst-section h3,.dst-section p{margin:0}.dst-section h2{font-size:18px;line-height:26px;font-weight:600;letter-spacing:-.01em;color:var(--dsw-alias-label-primary)}.dst-section h3{font-size:14px;line-height:22px;font-weight:600;color:var(--dsw-alias-label-primary)}
.dst-intro,.dst-hint{color:var(--dsw-alias-label-tertiary)}.dst-intro{max-width:640px;font-size:14px;line-height:22px}.dst-hint{font-size:12px;line-height:18px}
.dst-hero{display:flex;align-items:flex-start;justify-content:space-between;gap:20px}.dst-hero>div{display:flex;flex-direction:column;gap:4px}
.dst-status{display:flex;gap:8px;flex-wrap:wrap;margin:2px 0 4px}.dst-badge{display:inline-flex;align-items:center;gap:7px;border:1px solid var(--dsw-alias-border-l2);border-radius:14px;padding:4px 10px;font-size:12px;line-height:18px;color:var(--dsw-alias-label-secondary);background:var(--dsw-alias-bg-layer-1)}.dst-badge:before{content:"";width:7px;height:7px;border-radius:50%;background:var(--dsw-alias-state-error-primary)}.dst-badge--ok:before{background:var(--dsw-alias-state-success-primary)}
.dst-progress{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:2px 0 4px;padding:0;list-style:none}.dst-progress li{display:flex;align-items:center;gap:8px;min-width:0;padding:9px 10px;border:1px solid var(--dsw-alias-border-l2);border-radius:9px;color:var(--dsw-alias-label-tertiary);font-size:12px;line-height:18px}.dst-progress li span,.dst-step{display:inline-flex;flex:0 0 auto;align-items:center;justify-content:center;width:22px;height:22px;border-radius:50%;background:var(--dsw-alias-bg-module-platform);color:var(--dsw-alias-label-secondary);font-size:12px;font-weight:600}.dst-progress li.is-current{border-color:var(--dsw-alias-brand-primary);color:var(--dsw-alias-label-primary)}.dst-progress li.is-done{color:var(--dsw-alias-state-success-primary)}.dst-progress li.is-done span{background:var(--dsw-alias-state-success-primary);color:var(--dsw-alias-label-primary-foreground)}
.dst-card{box-sizing:border-box;display:flex;flex-direction:column;gap:14px;padding:18px;border:1px solid var(--dsw-alias-border-l2);border-radius:12px;background:transparent}.dst-card>h3{padding-bottom:2px}.dst-card--primary{border-color:var(--dsw-alias-border-l3);background:var(--dsw-alias-bg-module-platform)}.dst-card--muted{opacity:.72}.dst-card-title{display:flex;align-items:flex-start;gap:11px}.dst-card-title>div{display:flex;flex-direction:column;gap:2px}.dst-step{margin-top:0;background:var(--dsw-alias-brand-primary);color:var(--dsw-alias-label-primary-foreground)}
.dst-row{display:grid;grid-template-columns:minmax(170px,210px) minmax(260px,1fr);gap:20px;align-items:start}.dst-field{display:flex;flex-direction:column;gap:3px}.dst-field label,.dst-row>label,.dst-toggle{font-size:13px;line-height:20px;font-weight:550;color:var(--dsw-alias-label-primary)}
.dst-input,.dst-select,.dst-textarea{width:100%;box-sizing:border-box;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;background:var(--dsw-specific-input-major);color:var(--dsw-alias-label-primary);padding:8px 11px;font:inherit;font-size:14px;line-height:22px;transition:border-color var(--ds-transition-duration-fast) var(--ds-ease-in-out),box-shadow var(--ds-transition-duration-fast) var(--ds-ease-in-out)}.dst-input,.dst-select{height:40px}.dst-textarea{min-height:76px;resize:vertical}
.dst-input:hover:not(:disabled),.dst-select:hover:not(:disabled),.dst-textarea:hover:not(:disabled){border-color:var(--dsw-alias-border-l3)}.dst-input:focus,.dst-select:focus,.dst-textarea:focus{outline:none;border-color:var(--dsw-alias-brand-primary);box-shadow:0 0 0 2px color-mix(in srgb,var(--dsw-alias-brand-primary) 18%,transparent)}.dst-input:disabled,.dst-select:disabled,.dst-textarea:disabled{opacity:.5;cursor:not-allowed}
.dst-toggle{display:flex;gap:10px;align-items:center}.dst-toggle input{width:16px;height:16px;margin:0;accent-color:var(--dsw-alias-brand-primary)}.dst-toggle span{display:flex;flex-direction:column;gap:1px}.dst-toggle small,.dst-choice small{color:var(--dsw-alias-label-tertiary);font-size:12px;line-height:18px;font-weight:400}.dst-card>.dst-hint{padding-left:26px}
.dst-status-row,.dst-inline-actions{display:flex;align-items:center;gap:9px;flex-wrap:wrap}.dst-status-row code,.dst-permission-list code{font-size:12px;color:var(--dsw-alias-label-secondary)}.dst-link-button{border:0;background:transparent;color:var(--dsw-alias-brand-primary);padding:5px 2px;font:inherit;font-size:13px;cursor:pointer}.dst-details{border-top:1px solid var(--dsw-alias-border-l2);padding-top:12px}.dst-details summary{color:var(--dsw-alias-label-secondary);font-size:13px;cursor:pointer}.dst-details[open]{display:flex;flex-direction:column;gap:12px}.dst-callout{padding:10px 12px;border-radius:8px;background:var(--dsw-alias-bg-module-platform);color:var(--dsw-alias-label-secondary);font-size:12px;line-height:18px}.dst-callout--warning{border-left:3px solid var(--dsw-alias-state-warn-primary)}
.dst-permission-list{display:flex;flex-direction:column;gap:9px}.dst-permission-list>div{display:grid;grid-template-columns:20px minmax(155px,auto) 1fr;gap:8px;align-items:center;color:var(--dsw-alias-label-secondary);font-size:12px;line-height:18px}.dst-check{display:inline-flex;align-items:center;justify-content:center;width:18px;height:18px;border-radius:50%;background:var(--dsw-alias-state-error-primary);color:var(--dsw-alias-label-primary-foreground);font-size:11px;font-weight:700}.dst-check.is-done{background:var(--dsw-alias-state-success-primary)}.dst-check.is-info{background:var(--dsw-alias-brand-primary)}
.dst-fieldset{display:flex;flex-direction:column;gap:10px;margin:0;border:0;padding:0}.dst-fieldset legend{margin-bottom:7px;font-size:13px;font-weight:550}.dst-choice{display:flex;align-items:flex-start;gap:10px;padding:11px;border:1px solid var(--dsw-alias-border-l2);border-radius:9px;cursor:pointer}.dst-choice:has(input:checked){border-color:var(--dsw-alias-brand-primary);background:var(--dsw-alias-bg-module-platform)}.dst-choice input{margin-top:3px;accent-color:var(--dsw-alias-brand-primary)}.dst-choice span{display:flex;flex-direction:column;gap:2px;font-size:13px}.dst-launch{margin:2px -4px -4px;padding:14px;border-radius:9px;background:var(--dsw-alias-bg-module-platform)}
.dst-actions{position:sticky;bottom:-1px;z-index:1;display:flex;align-items:center;gap:12px;padding:12px 0 2px;background:linear-gradient(transparent 0,var(--dsw-alias-bg-layer-1) 28%)}.dst-button{box-sizing:border-box;display:inline-flex;align-items:center;justify-content:center;height:36px;border:0;border-radius:18px;background:var(--dsw-alias-button-primary-fill);color:var(--dsw-alias-label-primary-foreground);padding:0 16px;font:inherit;font-size:14px;line-height:22px;font-weight:500;text-decoration:none;cursor:pointer}.dst-button--secondary{border:1px solid var(--dsw-alias-border-l2);background:transparent;color:var(--dsw-alias-label-primary)}.dst-button:hover:not(:disabled){background:var(--dsw-alias-button-primary-hover)}.dst-button--secondary:hover:not(:disabled){background:var(--dsw-alias-bg-module-platform)}.dst-button:focus-visible{outline:none;box-shadow:0 0 0 2px var(--dsw-alias-border-l3)}.dst-button:disabled{opacity:.4;cursor:default}.dst-error,.dst-success{font-size:12px;line-height:18px}.dst-error{color:var(--dsw-alias-state-error-primary)}.dst-success{color:var(--dsw-alias-state-success-primary)}
@media(max-width:720px){.dst-row{grid-template-columns:1fr;gap:7px}.dst-card{padding:14px}.dst-card>.dst-hint{padding-left:0}.dst-progress{grid-template-columns:1fr}.dst-hero{flex-direction:column}.dst-permission-list>div{grid-template-columns:20px 1fr}.dst-permission-list>div>span:last-child{grid-column:2}}
`

/** Install the stylesheet and return its scoped disposer. */
export function adoptStyles(): () => void {
  if (document.getElementById(ID) !== null) return () => undefined
  const style = document.createElement('style')
  style.id = ID
  style.textContent = CSS
  document.head.append(style)
  return () => { style.remove() }
}
